# Generated by Django 3.1.3 on 2020-11-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_hour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'provider', 'hour')},
        ),
    ]
