# Generated by Django 3.1.1 on 2020-11-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20201111_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.CharField(choices=[('La Vete', 'La Vete'), ('Medipet', 'Medipet'), ('El Establo', 'El Establo'), ('Intensivet', 'Intensivet')], default='La Vete', max_length=30),
        ),
    ]
